version: "3.8"
services:
  frontend:
    build:
      context: /home/wille/Desktop/ThyraSec/frontend # Absolute path to your frontend directory
      dockerfile: Dockerfile # Assuming the Dockerfile is in the frontend root
    ports:
      - "5173:80"

  backend:
    build:
      context: /home/wille/Desktop/ThyraSec/thyra # Absolute path to your backend directory
      dockerfile: Dockerfile # Assuming the Dockerfile is in the backend root
    ports:
      - "8082:8082"
  db:
    image: postgres
    environment:
      POSTGRES_DB: thyra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
